
#ifndef __ECU_TXRX_CAN_H__
#define __ECU_TXRX_CAN_H__

#include "datatypes.h"
#include "can.h"

extern void ECU_ACC_382_Read_Msg();
extern void ECU_ACC_382_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2A4_Read_Msg();
extern void ECU_GW_2A4_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_765_Read_Msg();
extern void ECU_GW_765_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_76D_Read_Msg();
extern void ECU_ACC_76D_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_791_Read_Msg();
extern void ECU_GW_791_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_799_Read_Msg();
extern void ECU_ACC_799_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_752_Read_Msg();
extern void ECU_GW_752_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_75A_Read_Msg();
extern void ECU_LAS_75A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_763_Read_Msg();
extern void ECU_GW_763_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_76B_Read_Msg();
extern void ECU_LAS_76B_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_592_Read_Msg();
extern void ECU_LAS_592_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_594_Read_Msg();
extern void ECU_ACC_594_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_50_Read_Msg();
extern void ECU_GW_50_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_170_Read_Msg();
extern void ECU_GW_170_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_180_Read_Msg();
extern void ECU_GW_180_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_244_Read_Msg();
extern void ECU_ACC_244_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_278_Read_Msg();
extern void ECU_GW_278_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_298_Read_Msg();
extern void ECU_GW_298_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_307_Read_Msg();
extern void ECU_ACC_307_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_312_Read_Msg();
extern void ECU_ACC_312_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_340_Read_Msg();
extern void ECU_GW_340_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_347_Read_Msg();
extern void ECU_GW_347_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_365_Read_Msg();
extern void ECU_GW_365_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_366_Read_Msg();
extern void ECU_GW_366_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_387_Read_Msg();
extern void ECU_GW_387_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_390_Read_Msg();
extern void ECU_GW_390_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_396_Read_Msg();
extern void ECU_GW_396_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_507_Read_Msg();
extern void ECU_GW_507_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_516_Read_Msg();
extern void ECU_GW_516_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_530_Read_Msg();
extern void ECU_GW_530_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_187_Read_Msg();
extern void ECU_GW_187_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_197_Read_Msg();
extern void ECU_GW_197_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_194_Read_Msg();
extern void ECU_GW_194_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_17D_Read_Msg();
extern void ECU_GW_17D_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_17E_Read_Msg();
extern void ECU_GW_17E_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_1BA_Read_Msg();
extern void ECU_ACC_1BA_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_20B_Read_Msg();
extern void ECU_GW_20B_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_24F_Read_Msg();
extern void ECU_GW_24F_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_28B_Read_Msg();
extern void ECU_GW_28B_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2D1_Read_Msg();
extern void ECU_GW_2D1_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2DE_Read_Msg();
extern void ECU_GW_2DE_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2E6_Read_Msg();
extern void ECU_GW_2E6_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_31A_Read_Msg();
extern void ECU_ACC_31A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_355_Read_Msg();
extern void ECU_GW_355_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3AF_Read_Msg();
extern void ECU_GW_3AF_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3B3_Read_Msg();
extern void ECU_GW_3B3_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3BD_Read_Msg();
extern void ECU_GW_3BD_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3C4_Read_Msg();
extern void ECU_GW_3C4_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3FD_Read_Msg();
extern void ECU_GW_3FD_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3FF_Read_Msg();
extern void ECU_GW_3FF_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_51E_Read_Msg();
extern void ECU_GW_51E_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_693_Read_Msg();
extern void ECU_ACC_693_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_694_Read_Msg();
extern void ECU_LAS_694_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_452_Read_Msg();
extern void ECU_LAS_452_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_28C_Read_Msg();
extern void ECU_GW_28C_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_331_Read_Msg();
extern void ECU_GW_331_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_1AF_Read_Msg();
extern void ECU_GW_1AF_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_320_Read_Msg();
extern void ECU_GW_320_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_39A_Read_Msg();
extern void ECU_LAS_39A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_310_Read_Msg();
extern void ECU_GW_310_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3E8_Read_Msg();
extern void ECU_GW_3E8_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3E7_Read_Msg();
extern void ECU_GW_3E7_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_38A_Read_Msg();
extern void ECU_GW_38A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_249_Read_Msg();
extern void ECU_GW_249_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_262_Read_Msg();
extern void ECU_GW_262_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_334_Read_Msg();
extern void ECU_GW_334_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_395_Read_Msg();
extern void ECU_GW_395_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_18A_Read_Msg();
extern void ECU_GW_18A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_24A_Read_Msg();
extern void ECU_GW_24A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_25C_Read_Msg();
extern void ECU_GW_25C_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2D7_Read_Msg();
extern void ECU_GW_2D7_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_341_Read_Msg();
extern void ECU_GW_341_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3D6_Read_Msg();
extern void ECU_GW_3D6_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3D8_Read_Msg();
extern void ECU_GW_3D8_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3DE_Read_Msg();
extern void ECU_GW_3DE_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3EE_Read_Msg();
extern void ECU_GW_3EE_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_6B0_Read_Msg();
extern void ECU_GW_6B0_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_2D3_Read_Msg();
extern void ECU_ACC_2D3_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_301_Read_Msg();
extern void ECU_ACC_301_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_30C_Read_Msg();
extern void ECU_LAS_30C_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2E2_Read_Msg();
extern void ECU_GW_2E2_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2E3_Read_Msg();
extern void ECU_GW_2E3_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2C9_Read_Msg();
extern void ECU_GW_2C9_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_761_Read_Msg();
extern void ECU_GW_761_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_57D_Read_Msg();
extern void ECU_GW_57D_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_518_Read_Msg();
extern void ECU_GW_518_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_2AE_Read_Msg();
extern void ECU_GW_2AE_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_3D9_Read_Msg();
extern void ECU_LAS_3D9_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_LAS_3DB_Read_Msg();
extern void ECU_LAS_3DB_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_371_Read_Msg();
extern void ECU_GW_371_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_31C_Read_Msg();
extern void ECU_GW_31C_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_10A_Read_Msg();
extern void ECU_GW_10A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_BDC_400_Read_Msg();
extern void ECU_BDC_400_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_ACC_453_Read_Msg();
extern void ECU_ACC_453_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_7DF_Read_Msg();
extern void ECU_GW_7DF_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_15D_Read_Msg();
extern void ECU_GW_15D_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_10F_Read_Msg();
extern void ECU_GW_10F_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_32A_Read_Msg();
extern void ECU_GW_32A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_3BE_Read_Msg();
extern void ECU_GW_3BE_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);
extern void ECU_GW_37A_Read_Msg();
extern void ECU_GW_37A_Send_Msg(CANHandle_t Direction,uint16_t Msgtype);

#endif
